apiVersion: v1
kind: Pod
metadata:
  namespace: oss-agent
  labels:
    containers: maven
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oss-presto-dynamic-managed-ng
  serviceAccountName: oss-agent
  containers:
  - name: maven
    image: maven:3.8.6-openjdk-8-slim
    tty: true
    resources:
      requests:
        memory: "3Gi"
        cpu: "500m"
      limits:
        memory: "3Gi"
        cpu: "500m"
    env:
    - name: MAVEN_OPTS
      value: "-Xmx3g -Xms3g"
    command:
    - cat
