name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'
      - name: Set up Homebrew
        if: matrix.os == 'macos-latest'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install GNU binutils
        if: matrix.os == 'macos-latest'
        run: |
          brew install binutils
          brew install patchelf
          echo /opt/homebrew/opt/binutils/bin >> $GITHUB_PATH
      - name: Install libaio-dev
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get install -y libaio-dev
      - name: Cache mysql downloads
        uses: actions/cache@v4
        with:
          path: testing-mysql-server-8/dist
          key: mysql-downloads-${{ hashFiles('**/repack-mysql-8.sh') }}
      - name: Run Maven install
        run: |
          echo $PATH
          ./mvnw -B --no-transfer-progress clean install -pl testing-mysql-server-8 -am
